name: GoAnime CI

on:
  push:
    branches: [ main, dev, ipc ]
  pull_request:
    branches: [ main, dev, ipc ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        go-version: [ '1.25.x' ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y mpv

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install mpv -y

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install mpv

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          install-mode: go
          args: --timeout=5m ./...

      - name: Run tests
        run: go test -v -coverprofile=coverage.out ./...